// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ickevbvqlzjnzzynohup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlja2V2YnZxbHpqbnp6eW5vaHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTMxMjAsImV4cCI6MjA3MzQ4OTEyMH0.-5ilpZ0hHMEMHRBicaMGXb7aFdxv5LojkrJMgb-UzZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});